### ISSUE TITLE
NullPointerException checking response status

### ISSUE THREAD

**Issue by jethron** [opsgenie/opsgenie-jenkins-plugin#3]
Using 1.2, latest version in Jenkins. All builds using this plugin end with:
```
09:01:44 Sending job data to OpsGenie...
09:01:44 java.lang.NullPointerException
09:01:44 	at com.opsgenie.integration.jenkins.OpsGenieNotificationService.checkResponse(OpsGenieNotificationService.java:73)
09:01:44 	at com.opsgenie.integration.jenkins.OpsGenieNotificationService.sendAfterBuildData(OpsGenieNotificationService.java:249)
09:01:44 	at com.opsgenie.integration.jenkins.OpsGenieNotifier.perform(OpsGenieNotifier.java:78)
09:01:44 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
09:01:44 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
09:01:44 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
09:01:44 	at hudson.model.Build$BuildExecution.post2(Build.java:186)
09:01:44 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
09:01:44 	at hudson.model.Run.execute(Run.java:1752)
09:01:44 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
09:01:44 	at hudson.model.ResourceController.execute(ResourceController.java:97)
09:01:44 	at hudson.model.Executor.run(Executor.java:429)
```
Looks like this was fixed and reverted?
Is there a status update on this?
Can we expect a new plugin release at some point?

**Comment by bkaganyildiz** [comment]
Hi @jethron, opsgenie-plugin forked by jenkins and for current master please check https://github.com/jenkinsci/opsgenie-plugin/commits/master . Sorry for inconvenience. There is an issue for updating plugin and jenkins integration respectively but I can not give ETA.

**Comment by vitalibertas** [comment]
Why are the latest builds not available for update via Jenkins?  We are also seeing this exception regularly.  Has this been given priority yet?

**Comment by cglrkn** [comment]
Hi, we are going to work on updating the plugin on Jenkins soon. Sorry for the inconvenience.
